version: "3.9"
services:

  sql:
    container_name: sql
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Work060804"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql
volumes:
  sqlvolume: